### ISSUE TITLE
Cloned Noisy Typer and replaced the sounds

### ISSUE THREAD

**Issue by shokuninstudio** [iAladdin/NoisyTyper-Swift#4]
Hello iAladdin

I have cloned Noisy Typer and replaces the typewriter sounds with keyboard clicks from iOS. The repo can be found here below:

https://github.com/shokuninstudio/Noisy-Fruit-Swift-master

I find that there is a sound lag when typing. Any help you can give to fix the lag would be very appreciated! :)

Thanks for the great work.

**Comment by ninose11** [comment]
Hi shokonuninstudio, would it be possible for you to update this program to 64-bit? I contacted the original maker of the program but he doesn't reply.  I love this program so much for it's typewriter sounds. But unfortunately it's 32 bit which means it won't work on Mac OS  Catalina.

**Comment by iAladdin** [comment]
@ninose11 I'll update later, thanks for the suggestion. 

@shokuninstudio Can you give me the reproduce steps? 
and one more question, can I merge the two project sound resources and icons into one project? 
thank you for your work!

**Comment by shokuninstudio** [comment]
@ninose11 I find it works in Catalina. In Noisy Fruit I only converted the Swift to version 5 and changed the icons and sounds.

@iAladdin In Noisy Typer there wasn't any apparent lag when typing fast. But after changing the sounds in Noisy Fruit sometimes keystrokes won't produce a sound effect, but it does require very fast typing to reproduce. Please feel free to take anything you want from the project. It would be a really good feature to let users choose different sound effects libraries or load their own sound effects.

**Comment by ninose11** [comment]
@shokuninstudio Wow! That's great news! I was afraid that the program being 32-bit wouldn't work. Relieved to hear that! I was thinking of not updating to Catalina out of fear that there would be no way to get Noisy Typer to work. Thank you for verifying that it does, :)

@iAladdin Unfortunately, I know nothing about programming or even how to update a 32 to 64 bit program if i had to.  But I did find this on Apple's web site:

https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture

Thanks again @shokuninstudio and @iAladdin

**Comment by shokuninstudio** [comment]
@ninose11 Just one correction : I didn't download the Noisy Typer app that is available. I downloaded the Xcode project and compiled it myself. Maybe Xcode converted it to 64 bit without me knowing. Please find the app attached:

[NoisyTyper.app.zip](https://github.com/iAladdin/NoisyTyper-Swift/files/3562758/NoisyTyper.app.zip)

**Comment by iAladdin** [comment]
@ninose11 @shokuninstudio 

[NoisyTyper.zip](https://github.com/iAladdin/NoisyTyper-Swift/files/3562780/NoisyTyper.zip)

I have fixed bugs and try to build with 64bit, please try it!

**Comment by iAladdin** [comment]
@shokuninstudio I using the sounds file and artwork from your version.

If it's okay, I'll add your these credits to this project.

**Comment by shokuninstudio** [comment]
Thanks, I'm trying now. It would be better to change 'iPhone' to 'iOS' in this line:

 var themeItem3:NSMenuItem = NSMenuItem(title:"iOS", action: #selector(changeTheme), keyEquivalent:"")

**Comment by ninose11** [comment]
@iAladdin OK will be sure to do so. Thank you so much for your help with this! I think a lot of people who love this program will be thrilled to know that it can be updated to 64bit for Catalina. I would mention it on the original Noisy Typer page and on youtube. Thank you again! :)

**Comment by iAladdin** [comment]
Sounds good!
@shokuninstudio maybe you can fix it and then make a pull request?

then I can add you to readme later

**Comment by iAladdin** [comment]
> @iAladdin OK will be sure to do so. Thank you so much for your help with this! I think a lot of people who love this program will be thrilled to know that it can be updated to 64bit for Catalina. I would mention it on the original Noisy Typer page and on youtube. Thank you again! :)

It's a great pleasure if you can use it. Please let me know the result, thank you! I don't upgrade to Catalina yet.

**Comment by shokuninstudio** [comment]
If I change 'iPhone' to 'iOS' I receive in Line 248 **'Thread 1: Fatal error: Index out of range**

func playTestSound(){
        soundKey[0]?.pan = 0.3

**Comment by iAladdin** [comment]
@shokuninstudio 
Sure, blame me. I mixed UI and data logic, they shared the title of the menu item, when you change "iPhone" to "iOS", you need to change all "iPhone" to "iOS". Or you can split logic dependency.

About the lag problem:

There is a trick: I try to keep each sound play whole length, not clipped by next type key action, so I add a little logic to check the last sound is playing or not. if it's still playing, I'll randomly pick next sound to play. So I just append more standard sounds to let app always have idle sound.

**Comment by shokuninstudio** [comment]
I found three instances of 'iPhone'. Maybe I missed one.

There's no lag in this new version. It's really good!

Here is the code converted to Swift 5. You just need to change the Developer ID back to yours.
[NoisyTyper-Swift-master.zip](https://github.com/iAladdin/NoisyTyper-Swift/files/3562805/NoisyTyper-Swift-master.zip)

**Comment by iAladdin** [comment]
@shokuninstudio great! I can do it manually, but if you make a pull request, the system will add you as a contributor to this project. It's great fun!

No offense, if you wanna know how to make a pull request, if you need this, you can check this video  https://www.youtube.com/watch?v=nT8KGYVurIU

**Comment by shokuninstudio** [comment]
@iAladdin It's no offense :) I just started with Github yesterday and am completely beginner. I only want to learn to port old 1980s games that nobody is porting :)

**Comment by iAladdin** [comment]
@shokuninstudio It's great project. We all love the classic game. Anyway, if you have interest make a pull request, anytime is okay!

If your project have any progress, please let me know, I wanna be a tester for that!

**Comment by shokuninstudio** [comment]
Thanks. For now, everything is good and no changes needed. It works in Catalina and performance is perfect. Let's see what happens after some more macOS updates.

**Comment by ninose11** [comment]
> Thanks. For now, everything is good and no changes needed. It works in Catalina and performance is perfect. Let's see what happens after some more macOS updates.

Hi shokuninstudio, I just downloaded NoisyTyper-Swift-Master. The typing sounds work perfectly. But when you hit the delete key on the keyboard, the delete key sound lags a lot. Is there any way you can tweak it or fix it? Everything else (except for the delete key sound lagging) works perfectly. Thanks again very much for making this 64-bit! 👍 👍👍

**Comment by ninose11** [comment]
Hi shokuninstudio, I just downloaded NoisyTyper-Swift-Master. The typing sounds work perfectly. But when you hit the delete key on the keyboard, the delete key sound lags a lot. Is there any way you can tweak it or fix it? Everything else (except for the delete key sound lagging) works perfectly. Thanks again very much for making this 64-bit! 👍 👍👍

**Comment by shokuninstudio** [comment]
> Hi shokuninstudio, I just downloaded NoisyTyper-Swift-Master. The typing sounds work perfectly. But when you hit the delete key on the keyboard, the delete key sound lags a lot. Is there any way you can tweak it or fix it? Everything else (except for the delete key sound lagging) works perfectly. Thanks again very much for making this 64-bit! 👍 👍👍
> […](#)

@ninose11 Hi, I just tried it on Catalina and I don't have the lag in the backspace or delete. I don't have the latest update by iAladdin. I'm still using the one attached.
[NoisyTyper.zip](https://github.com/iAladdin/NoisyTyper-Swift/files/3694578/NoisyTyper.zip)

**Comment by ninose11** [comment]
Oh I see, perhaps I’m experiencing the lag because I’m still on Mojave? Will be sure to try it again as soon as OS Catalina is released.

**Comment by shokuninstudio** [comment]
> Oh I see, perhaps I’m experiencing the lag because I’m still on Mojave? Will be sure to try it again as soon as OS Catalina is released.
> […](#)

@ninose11 It should be the same on Mojave or Catalina. There might be system process on your machine that is using some CPU power and causing the delay. Check the Activity Monitor to see.

**Comment by ninose11** [comment]
OK then will do that, thanks very much for your help shokuninstudio.

**Comment by ninose11** [comment]
Hi Shokuninstudio, it's all good! Works perfectly now, no lag, thanks so much for making this 64bit Catalina compatible and even more user-friendly than it was before!

**Comment by ninose11** [comment]
Hi Shokuninstudio, just wanted to let you know that Noisy Typer no longer opens in Mac OS Catalina 10.15.6
When I ty to open it I keep getting this message: “NoisyTyper” will damage your computer. You should move it to the Trash."

![Screen Shot 2020-11-14 at 8 08 27 AM](https://user-images.githubusercontent.com/17236310/99147700-03a0ac00-2651-11eb-838f-9db49930c545.jpg)


Apple seems to think it's malware. Can you update your program so we can continue using it?

I love Noisy Typer so much, can't wait to solve this issue so I get back to using it. Thank you very much in advance.

**Comment by shokuninstudio** [comment]
> Hi Shokuninstudio, just wanted to let you know that Noisy Typer no longer opens in Mac OS Catalina 10.15.6
> When I ty to open it I keep getting this message: “NoisyTyper” will damage your computer. You should move it to the Trash."
> 
> ![Screen Shot 2020-11-14 at 8 08 27 AM](https://user-images.githubusercontent.com/17236310/99147700-03a0ac00-2651-11eb-838f-9db49930c545.jpg)
> 
> Apple seems to think it's malware. Can you update your program so we can continue using it?
> 
> I love Noisy Typer so much, can't wait to solve this issue so I get back to using it. Thank you very much in advance.

Hi, this is because Gatekeeper needs permission to launch it. Apple has gotten tighter in their requirements now. Do not report that version as malware otherwise Apple might block the developer's certificate.

To give the app permission go to Security & Privacy preference pane to allow any apps. Then click the Privacy tab, scroll down to Accessibility and enable NoisyTyper there. 

@iAladdin has a newer version that I haven't tried. He can confirm for you. Hopefully he submits NoisyTyper to the Mac App Store and then Apple will make it easier to install.

**Comment by ninose11** [comment]
Hi Shokuninstudio. I just downloaded your newer version of Noisy Typer (with the new icon of an old typewriter). But it still won’t open even though I made sure to check those settings in Privacy.
Noisy Typer tells me to check the checkbox in the Accessibility window, but it’s still not opening:

**Comment by shokuninstudio** [comment]
> Hi Shokuninstudio. I just downloaded your newer version of Noisy Typer (with the new icon of an old typewriter). But it still won’t open even though I made sure to check those settings in Privacy. Noisy Typer tells me to check the checkbox in the Accessibility window, but it’s still not opening:

You will have to wait for @iAladdin to answer. He is based in the Far East so he will be sleeping now.

**Comment by iAladdin** [comment]
@ninose11 
Thanks for using this app, I've released a version that is signed with a developer certificate, please try it out, thanks!

**Comment by ninose11** [comment]
Oops sorry, my mistake. Thank you.

**Comment by ninose11** [comment]
Hi sorry to bother you again. I'd love to redownload your great app "Noisy Typer" but it's no longer available here. Can you post an updated link? Thanks very much in advance, 😀
